### ISSUE TITLE
Empty rl_deepracer_coach_robomaker.py file?

### ISSUE THREAD

**Issue by jarrettj** [alexschultz/deepracer-for-dummies#1]
Hi,

There seems to be nothing in the rl_deepracer_coach_robomaker.py?

Probably an error with the init.sh that blanks the file.

<img width="732" alt="Screenshot 2019-07-19 at 11 00 48" src="https://user-images.githubusercontent.com/777547/61523353-7c1f3a80-aa14-11e9-8fd6-adc4289f601f.png">

**Comment by alexschultz** [comment]
Sorry about that. I need to check-in another file for it to work right. I'm currently traveling but I'll fix it when I get back. Until then you can comment out line 24 in the init file.

**Comment by jarrettj** [comment]
No worries, I simply git checked out the file :).

**Comment by alexschultz** [comment]
I checked in the missing file, thanks for pointing this out.
