### ISSUE TITLE
Cannot train my pretrained model

### ISSUE THREAD

**Issue by Vendetta37** [alexschultz/deepracer-for-dummies#14]
### [https://i.imgur.com/9klrABL.png](url)

**Comment by alexschultz** [comment]
Can you please elaborate a little more? I cannot tell what the issue is from that image and description alone.

**Comment by Vendetta37** [comment]
https://i.imgur.com/v5SvEm6.png
I solved that problem. But I have another problem now, I can load the pretrained model by ./start.sh. However, the reward seems being initialized. 
I found this line in the log 'Model folder /opt/ml/code/pretrained_checkpoint/checkpoint does not exist, creating', I don't know if this is the reason I cannot load the pretrained model properly. Thank you.
