### ISSUE TITLE
Seems cannot load pretrained model

### ISSUE THREAD

**Issue by Vendetta37** [alexschultz/deepracer-for-dummies#15]
these are the values of the reward supposed to be
https://i.imgur.com/MPAmU9M.png

what I get when I tried to retrain a model
https://i.imgur.com/GU1Tv7U.png

I've uncommented those two lines
https://i.imgur.com/jyTutI7.png

Besides the reward, the actions in retraining also look like random. I think I just started a new training instead of retraining a pretrained model? How to solve it? Thank you.

**Comment by gogov5** [comment]
how do you solve this problem?  thanks
