### ISSUE TITLE
Running on local server, can't connect to sagemaker logs

### ISSUE THREAD

**Issue by abstractSean** [alexschultz/deepracer-for-dummies#16]
Thanks for these tools. I'm a little new to all this, but I'm trying to get this to run on a local server. When I try to connect to the sagemaker logs using this command from start.sh:

`docker logs -f $(docker ps | awk ' /sagemaker/ { print $1 }')`

It doesn't find any containers with /sagemaker/. It appears the docker-compose is starting these 3 containers: minio, rl_coach, and robomaker. I'm confused where sagemaker is running and how to connect to it's logs. Any pointers on what I'm missing? I can VNC into robomaker without any issues.

**Comment by alexschultz** [comment]
Sagemaker is started programmatically from the Robomaker container, it's not started through the start script directly. Check the container logs for all of the other running containers to see if there are any errors. A few people have had the issue you are running into. In at least some of those cases it was that not all the prerequisites were properly installed.

**Comment by abogaziah** [comment]
did you solve that problem? 
I have it too
the logs shows this 
Waiting for SageMaker Redis server IP... Time elapsed: 565 seconds
it waits alot the this 
REQUIRED process [agent-9] has died!

**Comment by abogaziah** [comment]
I solved it by changing the awscli configure default region to 'us-west-2' and rerunning init.sh
 https://medium.com/@autonomousracecarclub/how-to-run-deepracer-locally-to-save-your-wallet-13ccc878687 
the medium article isn't very accurate and it would've saved me a lot of trouble if I followed this repo.
aws deepracer refers to the article not the repo,
so if you followed the article and that leaded you to the repo do it all again by following the documentation of the repo
