### ISSUE TITLE
Running evaluations.

### ISSUE THREAD

**Issue by jarrettj** [alexschultz/deepracer-for-dummies#19]
Hi,

Good day.

Been trying to figure out what is going on when I run an evaluation. My workflow is:
```
training/start.sh
...
training/stop.sh
...
evaluation/start.sh
...
evaluation/stop.sh
```

When I check the vncviewer, the car behaves completely different to what I read in the log analysis. So I checked the eval logs for the evaluation dockers. And it seems that it is not using the latest snapshot. Not only that, it overwrites the checkpoint. Before eval my checkpoint file is:
```
model_checkpoint_path: "85_Step-215377.ckpt"
all_model_checkpoint_paths: "81_Step-197464.ckpt"
all_model_checkpoint_paths: "82_Step-201475.ckpt"
all_model_checkpoint_paths: "83_Step-205622.ckpt"
all_model_checkpoint_paths: "84_Step-210502.ckpt"
all_model_checkpoint_paths: "85_Step-215377.ckpt"
```
after:
```
model_checkpoint_path: "0_Step-0.ckpt"
all_model_checkpoint_paths: "0_Step-0.ckpt"
```

I seem to be missing a step here I think? Could you please let me know what your workflow is like? Thanks. And kudos for the repo :).

Regards.

**Comment by alexschultz** [comment]
Hey Jarret, I don't use the evaluation script much but I would check the rl_deepracer_coach_robomaker.py file, for the RLEstimator on line 97. Do you have the hyperparameter[""pretrained_s3_bucket"] and hyperparameter["pretrained_s3_prefix"] set?

Those should tell robomaker to use the latest training run as a starting point. In addition to that after training, you probably need to run the set-last-run-to-pretrained script to get the evaluation to use the last training run.

**Comment by jarrettj** [comment]
Yes, sorry I forgot to close this issue. The part I had missed was uncommenting those lines to pretrain in the rl_deepracer_coach_robomaker.py file. 

So my workflow is:
```
training/start.sh
training/stop.sh
back-up-training-run.sh
set-last-run-to-pretrained.sh
evaluation/start.sh
evaluation/stop.sh
delete-last-run.sh
```

And repeat. Thanks.

**Comment by alexschultz** [comment]
glad you got it working
