### ISSUE TITLE
Can't back-up model

### ISSUE THREAD

**Issue by SW0BBR** [alexschultz/deepracer-for-dummies#20]
I have been really liking deepracer for dummies so far, but i have a problem. Every time after i have trained a model I run back-up-training-run.sh, and it says i cannot move my model to '/media/aschu/storage/deepracer-training/backup' because it does not exist.

Should i change it to a folder that does exist or is something going wrong?

thanks!

**Comment by alexschultz** [comment]
Hey sorry about that, yes you need to change the path to a directory on your system. I will try to fix this later so people don't run into the same issue.
