### ISSUE TITLE
the initialization stops when trying to create the agent 

### ISSUE THREAD

**Issue by abogaziah** [alexschultz/deepracer-for-dummies#22]
everything runs smoothly without errors but it freezes at that point of creating agent and I don't know what part of the project should I be looking into to solve this or what to google, please help ASAP
it worked before for like 20 episodes and gave an error then
![Screenshot from 2019-09-26 16-12-59](https://user-images.githubusercontent.com/33666625/65696285-39fc2000-e079-11e9-845a-1c8013c2d0f8.png)

**Comment by alexschultz** [comment]
Please look at the Docker logs for the various containers. I will try to get a better tutorial out there for how to do this but basically you can use the "docker ps" command to find all running containers, then for each of the containers run "docker logs <containerid>" to see the log output. 
There is likely more information in one of the logs.

**Comment by abogaziah** [comment]
thank you for responding 
I did looked at the logs, there's no errors.however, the traning started but after very long time. then it stopped after the 20th episode with this message 
![Screenshot from 2019-09-26 16-32-03](https://user-images.githubusercontent.com/33666625/65697698-a415c480-e07b-11e9-92f7-2be95aa9debc.png)

**Comment by alexschultz** [comment]
What GPU are you using?

**Comment by abogaziah** [comment]
930 mx

**Comment by alexschultz** [comment]
Can you paste the output from running "nvidia-smi" in the terminal before and during the training process?
I suspect that the card might not be able to handle the workload you're throwing at it.

**Comment by abogaziah** [comment]
it doesn't start, it gives the same message before even the training starts, I'll restart pc to free memory and try again 
that's before: 
![Screenshot from 2019-09-26 17-12-50](https://user-images.githubusercontent.com/33666625/65701550-c14d9180-e081-11e9-96cf-047c8169d8fd.png)

**Comment by abogaziah** [comment]
it doesn't start, but python is taking much of the gpu memory before the training starts. is that a memory leak problem? IDK! it increased form 31 to 600 and the training hasn't started yet
that's before running the script:
![Screenshot from 2019-09-26 17-56-00](https://user-images.githubusercontent.com/33666625/65704487-ed1f4600-e086-11e9-9e87-4d7080b08cc7.png)

**Comment by alexschultz** [comment]
I don't think it's a memory leak. Unfortunately 2GB is not a lot of memory so your system is going to struggle with the training process if it can handle it at all. You could try lowering the hyper parameter batch size or maybe shortening the number of episodes between training but I'm not sure if that will be enough to make this work.

**Comment by abogaziah** [comment]
Google offers free GPU training on colab, can we use that to train the model?
I'd try to look it up but there's no documentation for the project so I don't how exactly it works 
I'd love to contribute if you think that's achievable!

**Comment by alexschultz** [comment]
I don't know how that would work. You need to run the simulation somewhere in order to generate the data to train with.

**Comment by abogaziah** [comment]
can we use Open AI 's gym library for that purpose?
it's possible to create custom environments. I think that will make it run on colab gpu also

**Comment by alexschultz** [comment]
I don't think so, you really need Gazebo running to capture the data so that you can train the model.

**Comment by alexschultz** [comment]
closing for now, feel free to reopen if you're still having issues
