### ISSUE TITLE
Log analysis

### ISSUE THREAD

**Issue by antonino-tocco** [alexschultz/deepracer-for-dummies#23]
Hi, when I want to run log analysis it alwasy show me 799 episode and a lower iteration number.
Is the log loaded in the notebook correct or I must change file name?
If I must change file name, where is located the correct logs?
Thanks for your help

**Comment by alexschultz** [comment]
You need to change the file name. I walk through this in the video here:
https://youtu.be/CFNcKmtVRSI?t=1619

The log file should be located at the following location
/logs/*.log

**Comment by alexschultz** [comment]
if you still have issues feel free to re-open

**Comment by antonino-tocco** [comment]
Hi, I watched the video and change file based on your suggestion but log files seems empty.
The file have data but df.head() show nothing

**Comment by alexschultz** [comment]
did you run through the initial cells in the notebook?

**Comment by antonino-tocco** [comment]
Yes

Il giorno mer 9 ott 2019 alle 20:34 Alex Schultz <notifications@github.com>
ha scritto:

**Comment by alexschultz** [comment]
that seems strange, can you upload a sample log file so I can take a look?

**Comment by antonino-tocco** [comment]
Sure,
this is my log file: https://drive.google.com/open?id=11lgvRSUOaAndhino4wW8bWVKAulrXm7Y

**Comment by antonino-tocco** [comment]
Hi, have you any news?

**Comment by antonino-tocco** [comment]
Hi, I have found a solution. The logs file is in ../logs/ folder not in logs folder which refer to data directory as home directory

**Comment by alexschultz** [comment]
Glad you figured it out!
It sounds like you should be all set but if not then feel free to re-open the issue.
