### ISSUE TITLE
there are any parameters to set the evaluation to use certain model? 

### ISSUE THREAD

**Issue by gogov5** [alexschultz/deepracer-for-dummies#24]
Hi Alex
First of all, it is a really good job  for saving money, thank you

I have run the training and log-analysis smoothly, but when I run evaluation ./start.sh, I got a poor      results in the gazebo, the car can not follow the track. I want to know there are any parameters to set the evaluation to use certain model?  for example  'model_24.pb' or 'model_25.pb' in the folder '/bucket/rl-deepracer-pretrained/model'

now,my operations 1.  after training ,I execute ‘set last run to pretrained.sh’  2. set the pretrained model in file 'rl_deepracer_coach_robomaker.py',   then to execute the evaluation start     these operations are eight? 

thanks

**Comment by gogov5** [comment]
further more， I find that after steps 1. ‘set last run to pretrained.sh， 2  'delete last run.sh'  3, set using the pretrained model in file 'rl_deepracer_coach_robomaker.py'
4. I go back to start the training again, the car in the gazebo doesn't move, the training doesn't start , the GPU fan is quiet,   anything wrong with my operations?  thank you

**Comment by gogov5** [comment]
I comment the lines to close pretrained model in file 'rl_deepracer_coach_robomaker.py', the training start, the GPU fan buzz happily

**Comment by alexschultz** [comment]
are there any errors in the container outputs/logs?

**Comment by gogov5** [comment]
it seems no special errors output. and now it works well most time after updating the model_metadata.json to set a bigger speed.   
but still get a strange result sometimes when evaluation ,eg. the car goes far away from the track  ,but no reset,  special the last try in evaluation, it seems that the program is doing other 'saving' things and lost  the control of the car.

one question above,  if there are several db model, which one will be use when evaluation or training?

eg.  there are  model_23.pb, model_24.pb,model_25.pb, model_26.pb?  I note that there will lastest several checkpoints in the  pretrained folder

thanks

**Comment by gogov5** [comment]
I note that when the checkpoint saving each 20 episode, the car will lost control, and go out of track without reseting.  the saving is done, car recover and reset.  seems no impact on the training.
