### ISSUE TITLE
Adding the Plotly in to log-analysis docker image

### ISSUE THREAD

**Issue by cahya-wirawan** [alexschultz/deepracer-for-dummies#25]
Hi Alex,

Could you please add the Plotly (https://plot.ly/python/getting-started/) in to aschu/log-analysis docker image? Plotly is a really nice graphing library that can be used instead of matplotlib. I use it now as interactive track visualisation (https://github.com/aws-deepracer-community/aws-deepracer-workshops/pull/11). Currently my notebook use a docker image I have cloned from yours and adding it the Plotly. But it would be nice if your docker image has already this graphing library Plotly installed.

Thanks.

**Comment by alexschultz** [comment]
it's been added to the docker image
