### ISSUE TITLE
is there any other parameters should be set before running evaluation start.sh

### ISSUE THREAD

**Issue by gogov5** [alexschultz/deepracer-for-dummies#26]
Hi Alex，
when running the evaluation， the two parameters must be uncommented using pretrained？  

#"pretrained_s3_bucket": "{}".format(s3_bucket),
#"pretrained_s3_prefix": "rl-deepracer-pretrained"

is there any other parameters should be set before running evaluation start.sh

thanks

**Comment by alexschultz** [comment]
That is correct, you will need to uncomment those in order to evaluate a model. I don't believe there are other parameters that you need to set, besides the obvious ones like which track to use.
