### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by skalavala** [alexschultz/deepracer-for-dummies#40]
Alex,

What a fantastic job you've done! I am thoroughly impressed on how easy it is to set up deepracer locally, thanks to you and others who made it happen. It couldn't be any simpler!

It literally took under 2 minutes for me to run deepracer locally after setting up all the dependencies properly - dual boot, docker, docker-compose, nvidia drivers...etc. Of course there are many dependencies, and properly setting them up definitely takes longer, but you brought all of them together nicely packaged.

I know you mentioned that it worked for you with `nvidia-driver-410` driver set. In my case, I went with version 440, and I didn't see any issues at all. I hope it helps others who are setting up the environment.

Once again, great job documenting your repo!

**Comment by alexschultz** [comment]
Thanks for the kind words, the whole community has had a part in making this project work. As far as current efforts being done around DeepRacer, if you haven't already I would encourage you to join the [Slack community](http://join.deepracing.io/). There are a number of improvements that have been made to the code as well as new ways to run the setup.
