### ISSUE TITLE
Running Evaluation

### ISSUE THREAD

**Issue by controlsgeek** [alexschultz/deepracer-for-dummies#8]
I was able to run evaluation.launch present in deepracer_simulation package. 

It requires the addition of environment variable NUMBER_OF_TRIALS

And the evaluation can be started by roslaunch deepracer_simulation evaluation.launch

Regarding which model it chooses for evaluation is dependent on the model present in checkpoint.txt on the minio server. 

It will be helpful to have the evaluation function added.

**Comment by alexschultz** [comment]
Thanks for the input, I have updated the evaluation scripts so it should be working now.
